#!/usr/bin/env bash

# OFOX ENV
export FOX_DELETE_MAGISK_ADDON="1"
export FOX_DRASTIC_SIZE_REDUCTION="1"
export FOX_RECOVERY_BOOT_PARTITION="/dev/block/by-name/boot"
export FOX_RECOVERY_SYSTEM_PARTITION="/dev/block/mapper/system"
export FOX_RECOVERY_VENDOR_PARTITION="/dev/block/mapper/vendor"
export FOX_VARIANT="XOS"
export FOX_VERSION="R12.0_Beta"
export OF_ALLOW_DISABLE_NAVBAR="0"
export OF_DISABLE_MIUI_SPECIFIC_FEATURES="1"
export OF_DONT_PATCH_ENCRYPTED_DEVICE="1"
export OF_ENABLE_LPTOOLS="1"
export OF_FL_PATH1="/sys/devices/virtual/torch/torch/torch_level"
export OF_MAINTAINER="rama982"
export OF_NO_SAMSUNG_SPECIAL="1"
export OF_NO_TREBLE_COMPATIBILITY_CHECK="1"
export OF_SPLASH_MAX_SIZE="128"
export OF_SCREEN_H="2460"
export OF_STATUS_H="107"
export OF_STATUS_INDENT_LEFT="48"
export OF_STATUS_INDENT_RIGHT="48"
export OF_SKIP_ORANGEFOX_PROCESS="1"
export OF_VIRTUAL_AB_DEVICE="1"
